background {
    monitor =
    color = rgb(282c34)
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgb(94e2d5)
    inner_color = rgb(2e3440)
    font_color = rgb(cdd6f4)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    fail_color = rgb(f38ba8)
    fail_text = <i>$FAIL</i>
    halign = center
    valign = center
    position = 0, -50
}

label {
    monitor =
    text = cmd[update:1000] date +"%I:%M %p"
    color = rgb(94e2d5)
    font_size = 64
    font_family = CommitMono Nerd Font Mono
    halign = center
    valign = center
    position = 0, 100
}

label {
    monitor =
    text = Hi, $USER
    color = rgb(6c7086)
    font_size = 16
    font_family = CommitMono Nerd Font Mono
    halign = center
    valign = center
    position = 0, 30
}
