# vim:ft=kitty

## name: Catppuccin Mocha (OneDark BG)

foreground            #cdd6f4
background            #282c34

selection_foreground  #cdd6f4
selection_background  #3b4252

cursor                #cdd6f4
cursor_text_color     background

active_tab_background #282c34
active_tab_foreground #cdd6f4
active_tab_font_style bold
inactive_tab_background #282c34
inactive_tab_foreground #cdd6f4
inactive_tab_font_style normal

color0                #1b1f27
color8                #6c7086

color1                #f38ba8
color9                #f38ba8

color2                #a6e3a1
color10               #a6e3a1

color3                #f9e2af
color11               #f9e2af

color4                #89b4fa
color12               #89b4fa

color5                #cba6f7
color13               #cba6f7

color6                #fab387
color14               #fab387

color7                #cdd6f4
color15               #cdd6f4
