# vim:ft=kitty

## name: modus-vivendi

foreground            #ffffff
background            #000000

selection_foreground  #ffffff
selection_background  #2fafff

cursor                #ffffff
cursor_text_color     #000000

active_tab_background #000000
active_tab_foreground #ffffff
active_tab_font_style bold
inactive_tab_background #000000
inactive_tab_foreground #989898
inactive_tab_font_style normal

color0                #1e1e1e
color8                #535353

color1                #ff5f59
color9                #ff6b55

color2                #44bc44
color10               #70b900

color3                #d0bc00
color11               #fec43f

color4                #2fafff
color12               #79a8ff

color5                #feacd0
color13               #f78fe7

color6                #00d3d0
color14               #4ae2f0

color7                #989898
color15               #ffffff
